# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a Dot Product-type matrix multiplication. Understanding these properties will become useful as you move forward with machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication is distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [2]:
import numpy as np
import random

In [3]:
A = np.zeros((3, 3))
B = np.zeros((3, 3))
C = np.zeros((3, 3))

In [5]:
for x in range(0, A.shape[0]):
    for y in range(0, A.shape[1]):
        A[x][y] = random.randrange(1, 10)

In [6]:
for x in range(0, B.shape[0]):
    for y in range(0, B.shape[1]):
        B[x][y] = random.randrange(1, 10)

In [7]:
for x in range(0, C.shape[0]):
    for y in range(0, C.shape[1]):
        C[x][y] = random.randrange(1, 10)

In [16]:
print(A)
print('\n\n' ,B)
print('\n\n' ,C)

[[8. 9. 2.]
 [1. 1. 3.]
 [2. 2. 1.]]


 [[7. 6. 1.]
 [8. 2. 7.]
 [6. 5. 2.]]


 [[5. 2. 2.]
 [4. 9. 2.]
 [5. 9. 7.]]


In [17]:
# Your code here
LHS = A* (B+C)
RHS = (A*B + A*C)
print(LHS == RHS)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [18]:
LHS

array([[96., 72.,  6.],
       [12., 11., 27.],
       [22., 28.,  9.]])

In [19]:
RHS

array([[96., 72.,  6.],
       [12., 11., 27.],
       [22., 28.,  9.]])

## Associative Property - matrix multiplication is associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [2]:
# Your code here 
LHS = A*(B*C)
RHS = (A*B)*C
print()

## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [3]:
# Your code here 

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [4]:
# Your code here 

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [5]:
# Your code here 

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 